name: Generate Exploit SQLite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # once, every 4th hour
    - cron: '0 0 * * *'

jobs:
  getsqlite:
    name: Create an SQLite database
    runs-on: ubuntu-latest
    steps:
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y csvkit
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build SQLite
        run: $GITHUB_WORKSPACE/update
        shell: bash
      - uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: 'nightly'
          files: exploits.sqlite
